### ISSUE TITLE
undefined packet discriminator

### ISSUE THREAD

**Issue by phit** [Lunatrius/InGame-Info-XML#72]
InGameInfoXML-1.12.2-2.8.2.94-universal.jar

https://gist.github.com/phit/1c604dae353c9a1f0b8467d467603cee

see https://github.com/MinecraftForge/MinecraftForge/pull/4890

**Comment by TigerWalts** [comment]
The message type `MessageSeed` needs to be registered on both the server and the client. At the moment it is only being registered on the client: https://github.com/Lunatrius/InGame-Info-XML/blob/8bb2d1d90800744d567222f405e099cfc0515737/src/main/java/com/github/lunatrius/ingameinfo/network/PacketHandler.java#L13

**Comment by H4nSolo** [comment]
same Problem....
The Server will run 24h and then crashed after login on a User

`[Server thread/ERROR] [FML]: FMLIndexedMessageCodec exception caught
io.netty.handler.codec.EncoderException: java.lang.RuntimeException: Undefined discriminator for message type com.github.lunatrius.ingameinfo.network.message.MessageSeed in channel ingameinfoxml
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:106) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.handler.codec.MessageToMessageCodec.write(MessageToMessageCodec.java:116) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296) ~[minecraft_server.1.12.2.jar:?]
	at net.minecraftforge.fml.common.network.simpleimpl.SimpleNetworkWrapper.sendTo(SimpleNetworkWrapper.java:250) [SimpleNetworkWrapper.class:?]
	at com.github.lunatrius.ingameinfo.handler.PlayerHandler.onPlayerLogin(PlayerHandler.java:15) [PlayerHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_2283_PlayerHandler_onPlayerLogin_PlayerLoggedInEvent.invoke(.dynamic) [?:?]
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) [ASMEventHandler.class:?]
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:575) [FMLCommonHandler.class:?]
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:219) [pl.class:?]
	at shadows.fastbench.net.HijackedDedicatedPlayerList.initializeConnectionToPlayer(HijackedDedicatedPlayerList.java:19) [HijackedDedicatedPlayerList.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72) [NetworkDispatcher.class:?]
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205) [NetworkDispatcher$1.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285) [gw.class:?]
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180) [oz.class:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790) [MinecraftServer.class:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]
Caused by: java.lang.RuntimeException: Undefined discriminator for message type com.github.lunatrius.ingameinfo.network.message.MessageSeed in channel ingameinfoxml
	at net.minecraftforge.fml.common.network.FMLIndexedMessageToMessageCodec.encode(FMLIndexedMessageToMessageCodec.java:76) ~[FMLIndexedMessageToMessageCodec.class:?]
	at io.netty.handler.codec.MessageToMessageCodec$1.encode(MessageToMessageCodec.java:67) ~[minecraft_server.1.12.2.jar:?]
	at io.netty.handler.codec.MessageToMessageEncoder.write(MessageToMessageEncoder.java:88) ~[minecraft_server.1.12.2.jar:?]
	... 26 more`

**Comment by Lunatrius** [comment]
Actually a question. Why are you installing it on the server? You can safely remove it for the time being.

**Comment by phit** [comment]
so the client can get data like the seed from the server? :P
but yes already removed the mod from the server for us, still an issue that should be fixed

**Comment by Lunatrius** [comment]
Definitely. I'm surprised that this was changed during a regular update and not during a major release (1.12 -> 1.13).
