### ISSUE TITLE
Unknown Error when trying to save

### ISSUE THREAD

**Issue by CritFlaw** [Lunatrius/InGame-Info-XML#73]
I was told that I have to save the xml file from in-game in order to create an xml file that is then editable. When trying to run the /igi save command, I get "An unknown error occured while attempting to perform this command". 

Forge 2796
Mod 2.8.2,95
Minecraft 1.12.2

**Comment by BrisingrAerowing** [comment]
This is the error I get in the log:

```text
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.github.lunatrius.ingameinfo.command.InGameInfoCommand.execute(InGameInfoCommand.java:97) ~[InGameInfoCommand.class:?]
	at net.minecraft.command.CommandHandler.tryExecute(CommandHandler.java:119) [bj.class:?]
	at net.minecraftforge.client.ClientCommandHandler.executeCommand(ClientCommandHandler.java:95) [ClientCommandHandler.class:?]
	at net.minecraft.client.gui.GuiScreen.sendChatMessage(GuiScreen.java:422) [blk.class:?]
	at net.minecraft.client.gui.GuiScreen.sendChatMessage(GuiScreen.java:411) [blk.class:?]
	at net.minecraft.client.gui.GuiChat.keyTyped(SourceFile:81) [bkn.class:?]
	at net.minecraft.client.gui.GuiScreen.handleKeyboardInput(GuiScreen.java:558) [blk.class:?]
	at net.minecraft.client.gui.GuiScreen.handleInput(GuiScreen.java:512) [blk.class:?]
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:1759) [bib.class:?]
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098) [bib.class:?]
	at net.minecraft.client.Minecraft.run(Minecraft.java:3942) [bib.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:123) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_191]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_191]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_191]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by brisingraerowing** [comment]
Does your instance name have spaces in it? The filename  is being (incorrectly) URL encoded, turning spaces into %20, and is passed like that to the file handling stuff, causing the directory to not be found (as it's looking in the wrong place). I'm not sure if this mod is doing the encoding, or if some underlying API is.

**Comment by straef** [comment]
i know this is old, but the answer to this question is:

after typing "/igi save " into the chat, before pressing anything else, press the TAB key on your keyboard to have the command autocomplete for you. the first TAB should get you to "/igi save InGameInfo." and a second will complete the command in a valid way to "/igi save InGameInfo.xml" which is the complete and valid command.

i have not tested but it is likely that as long as you specify any valid filename.[xml,txt,json], and you are not experiencing the error that @BrisingrAerowing is describing, that you will be able to successfully save a config to a custom file.

alternatively, you could just get or create a "InGameInfo.xml" file and put it in your configs folder. the benefit to saving a config from the game is that it gives a starting point for the edits.
